server:
  port: 6969

# database setting
spring:
  # upload setting
  servlet:
    multipart:
      max-file-size: 3MB  # 1?? ??? ?? ??
      max-request-size: 20MB  # 1?? ??? ?? ? ?? ?? ??


  # mail setting
  mail:
    host: smtp.naver.com
    port: 465
    username: puppycompany
    password: gksrlqja1!
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
    default-encoding: UTF-8
    debug: true


  datasource:
    url: jdbc:mariadb://3.34.167.124:3306/mans
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl ??? ??? ????...
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # SQL ?? ??? ??? ??
    database: mysql

# log level setting
logging:
  level:
    root: info
    com.spring.manshubapi: debug
    org.hibernate.SQL: debug

manshuapi:
  mail:
    host: puppycompany@naver.com




