server:
  port: 1111

# database setting
spring:
  # upload setting
  servlet:
    multipart:
      max-file-size: 3MB  # 1?? ??? ?? ??
      max-request-size: 20MB  # 1?? ??? ?? ? ?? ?? ??


  # mail setting
  mail:
    host: smtp.naver.com
    port: 465
    username: juseong3051
    password: 630517zxc~!
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
    default-encoding: UTF-8
    debug: true


  datasource:
    url: jdbc:mariadb://localhost:3306/jpatest
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl ??? ??? ????...
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # SQL ?? ??? ??? ??
    database: mysql

# log level setting
logging:
  level:
    root: info
    com.study.event.api: debug
    org.hibernate.SQL: debug


# ??? ?? ??? ??
study:
  mail:
    host: juseong3051@naver.com

jwt:
  secret: vKFXxiTK4H/40bgLGPpWKrK/xyQ/oncDwasTv61WkxQLivDTpy54vNRncgh96+UP/xEq286NokTUsI09QI+90Q==